"use client";
import { useState, type FormEvent } from "react";
import { Fingerprint, Pencil, Pause, Play, Plus } from "lucide-react";
import { CreateTask } from "@/components/task-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { type Profile, useData } from "@/lib/data-store";
function ProfileEditor({ profile }: { profile?: Profile }) {
  const { addProfile, updateProfile } = useData(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name")).trim(); setSaving(true); setError("");
    try { if (profile) await updateProfile(profile.id, { name, status: String(form.get("status")) as Profile["status"] }); else await addProfile(name); setOpen(false); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось сохранить профиль"); }
    finally { setSaving(false); }
  }
  return <Dialog open={open} onOpenChange={value => { if (!saving) { setOpen(value); setError(""); } }}><DialogTrigger asChild><Button variant={profile ? "outline" : "default"} size={profile ? "sm" : "default"}>{profile ? <Pencil size={14} /> : <Plus size={16} />}{profile ? "Переименовать" : "Создать профиль"}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{profile ? "Имя профиля" : "Новый профиль"}</DialogTitle><DialogDescription>Мобильный отпечаток и файл сессии создаются при успешном запуске задачи.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="space-y-2"><Label htmlFor="profile-name">Название профиля</Label><Input id="profile-name" name="name" defaultValue={profile?.name} required maxLength={100} disabled={saving} placeholder="Основной мобильный профиль" /></div>{profile && <div className="space-y-2"><Label htmlFor="profile-status">Статус профиля</Label><select id="profile-status" name="status" defaultValue={profile.status} disabled={saving} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="new">Новый</option><option value="warming_up">Прогревается</option><option value="ready">Готов</option><option value="banned">Заблокирован</option></select></div>}{error && <p role="alert" className="form-error">{error}</p>}<DialogFooter><Button type="submit" disabled={saving}>{saving ? "Сохранение…" : "Сохранить профиль"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
export default function ProfilesPage() {
  const { profiles, tasks, updateProfile, pendingIds, loading } = useData(); const [query, setQuery] = useState("");
  const filtered = profiles.filter(profile => `${profile.name} ${profile.id}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="page-heading"><div><div className="eyebrow">ПЕРСИСТЕНТНЫЕ СЕССИИ</div><h1>Профили<span className="heading-dot">.</span></h1><p>Имена, сохранённые сессии и запуск прогрева.</p></div><ProfileEditor /></div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Input value={query} onChange={event => setQuery(event.target.value)} aria-label="Поиск профилей" placeholder="Имя или UUID профиля" className="max-w-sm" /><p className="text-sm text-muted-foreground">Профилей: {profiles.length} · активных: {profiles.filter(profile => profile.isEnabled && profile.status !== "banned").length}</p></div>
    <div className="grid gap-5 xl:grid-cols-2">{filtered.map(profile => {
      const related = tasks.filter(task => task.profileId === profile.id); const saved = profile.session?.state === "saved";
      return <section className="panel" key={profile.id}><div className="panel-heading"><div className="flex min-w-0 items-center gap-3"><Fingerprint size={22} className="shrink-0 text-primary" /><h2 className="truncate">{profile.name}</h2></div><Badge variant="outline" className={`status-badge ${profile.status === "banned" ? "status-failed" : profile.status === "ready" ? "status-completed" : "status-paused"}`}>{{ new: "Новый", warming_up: "Прогревается", ready: "Готов", banned: "Заблокирован" }[profile.status]}</Badge></div><div className="space-y-4 border-t px-6 py-5"><p className="break-all font-mono text-xs text-muted-foreground">{profile.id}</p><div className="grid gap-3 text-xs sm:grid-cols-2"><div><span className="text-muted-foreground">Сессия</span><p className="mt-1 text-sm">{saved ? `Сохранена · ${profile.session?.mobileOS?.toUpperCase() ?? "мобильная"}` : profile.session?.state === "unreadable" ? "Файл недоступен" : "Ещё не сохранена"}</p></div><div><span className="text-muted-foreground">Последнее сохранение</span><p className="mt-1 text-sm">{profile.session?.savedAt ? new Date(profile.session.savedAt).toLocaleString("ru-RU") : "—"}</p></div><div><span className="text-muted-foreground">Cookies / localStorage</span><p className="mt-1 text-sm">{profile.session?.cookiesCount ?? 0} cookies · {profile.session?.originsCount ?? 0} сайтов</p></div><div><span className="text-muted-foreground">Связанные задачи · прогревов: {profile.warmupScore}</span><p className="mt-1 text-sm">{related.length} задач · {related.reduce((sum, task) => sum + task.currentExecutions, 0)} выполнений</p></div></div><div className="flex flex-wrap gap-2"><ProfileEditor profile={profile} /><Button variant="outline" size="sm" disabled={pendingIds.has(profile.id)} onClick={() => void updateProfile(profile.id, { isEnabled: !profile.isEnabled }).catch(() => {})}>{profile.isEnabled ? <Pause size={14} /> : <Play size={14} />}{profile.isEnabled ? "Приостановить профиль" : "Включить профиль"}</Button>{profile.isEnabled && profile.status !== "banned" && <CreateTask initialMode="warmup" initialProfileId={profile.id} />}</div></div></section>;
    })}</div>{!filtered.length && <p className="rounded-lg border py-12 text-center text-sm text-muted-foreground">{loading ? "Загрузка профилей…" : "Профили не найдены. Создайте новый или добавьте задачу."}</p>}<p className="page-hint">Выключение профиля останавливает выполнение всех связанных задач. Cookies и localStorage остаются на сервере; в панели показаны только сведения о сессии.</p></>;
}
