"use client";
import { LockKeyhole } from "lucide-react";
import { IntegrationSettings } from "@/components/integration-settings";
import { ServiceStatus } from "@/components/service-status";
import { useData } from "@/lib/data-store";
import { donorSites } from "@/utils/donorSites";
export default function SettingsPage() {
  const { system } = useData();
  return <><div className="page-heading"><div><div className="eyebrow">ВАШЕ ПРОСТРАНСТВО</div><h1>Настройки<span className="heading-dot">.</span></h1><p>Интеграции, параметры и состояние автономного воркера.</p></div></div><ServiceStatus />
    <div className="settings-grid"><div className="space-y-6"><IntegrationSettings kind="openai" planMode={system?.planMode ?? "local"} /><IntegrationSettings kind="rucaptcha" />
      <section className="panel"><div className="panel-heading"><div><h2>Параметры запуска</h2><p>Текущая конфигурация сервиса</p></div></div><div className="grid gap-4 border-t p-6 text-sm sm:grid-cols-2"><div><span className="text-muted-foreground">План прямой задачи</span><p className="mt-1">{system?.planMode === "openai" ? "OpenAI API" : "Локально · без OpenAI"}</p></div><div><span className="text-muted-foreground">Устройства</span><p className="mt-1">Android / iOS · мобильные профили</p></div><div><span className="text-muted-foreground">Браузер</span><p className="mt-1">Chromium · {system?.headless ? "без окна" : "с окном"}</p></div><div><span className="text-muted-foreground">Прямое посещение</span><p className="mt-1">{system?.directVisitSeconds.join("–") ?? "60–120"} секунд</p></div><div><span className="text-muted-foreground">Поисковое посещение</span><p className="mt-1">1–5 минут</p></div><div><span className="text-muted-foreground">Прокси / смена IP</span><p className="mt-1">{system?.proxyScheme.toUpperCase() ?? "HTTP"} · пауза 15 секунд</p></div><div><span className="text-muted-foreground">Провайдер капчи</span><p className="mt-1">{system?.captchaProvider ?? "RuCaptcha"}</p></div></div><div className="border-t px-6 py-4"><p className="field-help">Параметры процесса задаются в окружении сервера и применяются при перезапуске воркера. Ключи из формы применяются без перезапуска.</p><p className="mt-3 text-sm">Запуск из папки приложения:</p><code className="mt-2 block rounded-md bg-background p-3 text-sm">pnpm worker</code><p className="field-help mt-2">Одна попытка: <code>pnpm worker:once</code>. Сохранение задачи само по себе не запускает процесс.</p></div></section>
      <section className="panel"><div className="panel-heading"><div><h2>Сайты для прогрева</h2><p>На каждый обход выбираются три из {donorSites.length} сайтов.</p></div></div><div className="grid gap-2 border-t p-6 text-xs text-muted-foreground sm:grid-cols-2">{donorSites.map(site => <span className="truncate" key={site}>{new URL(site).hostname}</span>)}</div></section>
    </div><aside className="settings-aside"><div className="small-icon"><LockKeyhole size={21} /></div><h2>Настройки интеграций</h2><p>Ключи хранятся в SQLite. В интерфейс возвращается только статус настройки.</p><p>{system?.planMode === "openai" ? "Прямые задачи используют OpenAI API. Ключ из базы имеет приоритет над ключом окружения." : "Прямые задачи используют локальный сценарий. Ключ OpenAI не нужен и запросы к API не отправляются."}</p><p>Параметры профиля генерируются автоматически. Сохранённая сессия повторно используется по выбранному профилю.</p></aside></div></>;
}
